GET http://localhost:3000/ponto

###

POST http://localhost:3000/ponto
Content-Type: application/json

{
  "funcionario_id": "a116317d-9b5d-44a1-a2c5-c4b66d760b11",
  "empresa_id": "fdc799c7-9ac4-43bd-9716-bc480fdd4a76"
}

### empresa

GET http://localhost:3000/empresa

###

POST http://localhost:3000/empresa
Content-Type: application/json

{
  "name": "Rubinhos enterprise",
  "cnpj": "1234567829033a1234"
}

### configuracoes

GET http://localhost:3000/configuracao

###

POST http://localhost:3000/configuracao
Content-Type: application/json

{
  "empresa_id": "550e8400-e29b-41d4-a716-446655440002",
  "min_semanal": "48h",
  "max_diaria": "18:00",
  "intervalo_min": "01:00",
  "intervalo_max": "02:00"
}

### funcionario

GET http://localhost:3000/funcionario

###

POST http://localhost:3000/funcionario
Content-Type: application/json

{
  "cargo": "Desenvolvedor WEB",
  "usuario_id": "524cf88b-539b-4624-bd7b-3919d5da9dd4",
  "empresa_id": "524cb88b-539b-4624-bd7b-3919d5da9dd4"
}

###

GET http://localhost:3000/funcionario/7d6bdcef-a17f-4b76-8301-270247de2af0

###

GET http://localhost:3000/funcionario/empresa/524cb88b-539b-4624-bd7b-3919d5da9dd4