### ponto
GET http://localhost:3000/ponto

###

POST http://localhost:3000/ponto
Content-Type: application/json

{
  "funcionario_id": "6f5013a5-e750-42e9-894a-f8a256df4571",
  "empresa_id": "cc1f6b5e-f5e9-489a-9c93-1addf2cad8b0"
}

###

PATCH http://localhost:3000/ponto
Content-Type: application/json

{
  "funcionario_id": "6f5013a5-e750-42e9-894a-f8a256df4571"
}

### empresa

GET http://localhost:3000/empresa

###

POST http://localhost:3000/empresa
Content-Type: application/json

{
  "name": "Rubinhsos enterprise",
  "cnpj": "123456782a9033a1234"
}

### configuracoes

GET http://localhost:3000/configuracao

###

POST http://localhost:3000/configuracao
Content-Type: application/json

{
  "empresa_id": "cc1f6b5e-f5e9-489a-9c93-1addf2cad8b0",
  "min_semanal": "48h",
  "max_diaria": "18:00",
  "intervalo_min": "01:00",
  "intervalo_max": "02:00"
}

### funcionario

GET http://localhost:3000/funcionario

###

POST http://localhost:3000/funcionario
Content-Type: application/json

{
  "cargo": "Desenvolvedor JAVA",
  "usuario_id": "a75e9794-b8d6-430e-a305-7ab642e3a78b",
  "empresa_id": "cc1f6b5e-f5e9-489a-9c93-1addf2cad8b0"
}

###

GET http://localhost:3000/funcionario/7d6bdcef-a17f-4b76-8301-270247de2af0

###

GET http://localhost:3000/funcionario/empresa/524cb88b-539b-4624-bd7b-3919d5da9dd4

### usuario

GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
  "nome": "Rubens",
  "email": "rubem@email.com",
  "senha": "123456",
  "tipo_usuario": "funcionario"
}